// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxlmaaimylatzccfxwmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bG1hYWlteWxhdHpjY2Z4d21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDc5MzQsImV4cCI6MjA3MzQyMzkzNH0.MEs81f7ejaGCQlibNNboiEPff8RmehD9BRCOFrF8UO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});